# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default=None, help_text='La catégorie', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categorie')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Produit')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, through='app.ProduitCategorie', to='app.Categorie'),
        ),
    ]
