# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180110_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='contributions',
            field=models.ManyToManyField(blank=True, default=None, related_name='contributions', to='app.Produit'),
        ),
    ]
