# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_personne_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='detail',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
