# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='produit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Produit'),
        ),
    ]
