# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_picture_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MoviePersonne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paie', models.BigIntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Movie')),
            ],
        ),
        migrations.AlterField(
            model_name='personne',
            name='cadeaux',
            field=models.ManyToManyField(blank=True, default=None, related_name='participants', to='app.Produit'),
        ),
        migrations.AddField(
            model_name='moviepersonne',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Personne'),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='films', through='app.MoviePersonne', to='app.Personne'),
        ),
    ]
